### ISSUE TITLE
所以什么是最好的语言？？

### ISSUE THREAD

**Issue by wb-hwang** [liuzirui1122/zhuoyao_radar#11]
PHP？？？然而不对，壮我大Java 也不对…

**Comment by wb-hwang** [comment]
PS 网站被扩散到贴吧了

**Comment by vitechliu** [comment]
成熟的程序员应该知道字符串处理要考虑大小写

**Comment by wb-hwang** [comment]
what ??昨天试了PHP、php、Php都不行。。今天就开付费了。。。

**Comment by vitechliu** [comment]
> what ??昨天试了PHP、php、Php都不行。。今天就开付费了。。。

加群太多太吵 不得已开付费 入群全部金额将用于打赏PR开发者
