### ISSUE TITLE
开了VPN科学上网之后无法查找妖灵了

### ISSUE THREAD

**Issue by Imagery007** [liuzirui1122/zhuoyao_radar#18]
关了VPN也不行

**Comment by vitechliu** [comment]
妖灵请求腾讯地图接口 vpn效果不一定好。
关了vpn不行 只能说接口这段时间崩了。。

**Comment by Imagery007** [comment]
> 妖灵请求腾讯地图接口 vpn效果不一定好。
> 关了vpn不行 只能说接口这段时间崩了。。

谢谢你的回答，可以说一下怎么搜索指定妖灵吗
