### ISSUE TITLE
发现大范围扫描的一些BUG

### ISSUE THREAD

**Issue by UMP45-Cake** [liuzirui1122/zhuoyao_radar#27]
wideSearchYaoling方法中的循环不应是for (var lat = startLat,j=0;j<depthtime;j++,startLat+=this.lat_range)，这样startLat会累计增加，导致扫描出来不是一块区域，应该是这样
`var startLng = this.location.longitude - (depth-1)*this.lng_range;
                    var startLat = this.location.latitude - (depth-1)*this.lat_range;

                    var depthtime = 2*depth-1;
                    for (var lng = startLng,i=0;i<depthtime;i++,lng+=this.lng_range) {
                        for (var lat = startLat,j=0;j<depthtime;j++,lat+=this.lat_range) {
                            
                            var loc = {
                                longitude:lng,
                                latitude:lat
                            };
                            this.wideSearchQueue.push(loc);
                        }
                    }
                    
                    this.wideProcess();`

**Comment by vitechliu** [comment]
widesearch.html这个东西只是我花几分钟写的一个测试 根本就没有上线功能也没有写完
大范围搜索的功能根本不在这里面

**Comment by UMP45-Cake** [comment]
好吧。我以为是隐藏功能。
