### ISSUE TITLE
大佬，关于新的限流有什么思路吗

### ISSUE THREAD

**Issue by qq6264214** [liuzirui1122/zhuoyao_radar#29]
0 0最近限流 搞的大范围有些地方搜不到，有点难受

**Comment by galleonsZcc** [comment]
你把轮询间隔改成5s就行了

**Comment by qq6264214** [comment]
说出来你可能不信，我把轮训间隔改成20s 甚至30s，我调试ws的时候还是有部分send之后没有返回消息

**Comment by galleonsZcc** [comment]
这个我也遇到过，你加点逻辑好了，socket send一段时间以后去查询消息有没有返回，如果没有返回就当断掉了，重新建立一个socket连接。
应该是前段时间腾讯服务器被刷爆了加了限流。

**Comment by qq6264214** [comment]
好的，一会儿我试试

**Comment by vitechliu** [comment]
> 好的，一会儿我试试

1.0 commit早就[包含这段](https://github.com/liuzirui1122/zhuoyao_radar/blob/master/src/mixins/socket.js)了。
```
//监听回应
if (socket.timeout) {
  clearTimeout(socket.timeout);
}
socket.timeout = setTimeout(() => {
  this.notify("操作过于频繁，请稍后再查询");
  // console.log(`ws.${socket.index} reconnect due to no response`);
  // socket.initSocket();
},socket.opts.maxTimeout);
```
只不过我试了重连没什么用，需要服务器支持多开ip

**Comment by qq6264214** [comment]
那大范围查询不是凉了。。多开ip一般不好搞啊

**Comment by qq6264214** [comment]
需要用分布式查询？

**Comment by qq6264214** [comment]
> > 好的，一会儿我试试
> 
> 1.0 commit早就[包含这段](https://github.com/liuzirui1122/zhuoyao_radar/blob/master/src/mixins/socket.js)了。
> 
> ```
> //监听回应
> if (socket.timeout) {
>   clearTimeout(socket.timeout);
> }
> socket.timeout = setTimeout(() => {
>   this.notify("操作过于频繁，请稍后再查询");
>   // console.log(`ws.${socket.index} reconnect due to no response`);
>   // socket.initSocket();
> },socket.opts.maxTimeout);
> ```
> 
> 只不过我试了重连没什么用，需要服务器支持多开ip

其实我已经不怎么玩这个游戏了0 0但是我觉得搞这个开发 挺有意思的

**Comment by kifgep** [comment]
clone到本地或者服务器的都没法打开了，咋整，多开IP没法搞，有大神有思路吗

**Comment by vitechliu** [comment]
1.2版本大范围限流问题已经基本解决

**Comment by qq6264214** [comment]
> 1.2版本大范围限流问题已经基本解决
我偷学一哈 大佬
