### ISSUE TITLE
作者好，我在研究地图wss的包结构，有一点搞不明白。

### ISSUE THREAD

**Issue by RedShameA** [liuzirui1122/zhuoyao_radar#36]
如下一个包:
E{"request_type":"1004","cfg_type":1,"requestid":1121338,"platform":0}
开头的E是怎么获得的呢

**Comment by RedShameA** [comment]
求回复啊，想不出来脑袋要炸了....

**Comment by RedShameA** [comment]
求回复啊，想不出来脑袋要炸了

**Comment by vitechliu** [comment]
开头4个字节要舍弃

**Comment by RedShameA** [comment]
> 开头4个字节要舍弃
首先感谢作者回复！！！
像你所说的这样，那么发送包的结构是什么呢，我应该是能看明白{}以及他们中间的结构了，包前头的实在是看不出来了。。。
求解惑~

**Comment by RedShameA** [comment]
> 开头4个字节要舍弃

抓到的包前4个字节上传是0000，接收是0001.后边4位看不懂了啊~~~

**Comment by vitechliu** [comment]
> > 开头4个字节要舍弃
> 
> 抓到的包前4个字节上传是0000，接收是0001.后边4位看不懂了啊~~~

除了前4个字节 后面就是正常的utf8-unicode编码的包文，你在网页控制台比如chrome f12里面监听websocket都能看到明文的

**Comment by RedShameA** [comment]
作者你看着第一行，这是chrome抓取的包的一部分
0000 0044 7b22 7265 7175 6573 745f 7479  
...D{"request_ty
是从7b开始才是  {
那前边的00 00 00 44是什么呢

而且我给wss发送{……}这样式的数据没有回应，里面的requestid是用13位时间戳模1234567，是不是我在这个地方有什么问题
发送的是{"request_type":"1004","cfg_type":1,"requestid":1121338,"platform":0}这一段，是在链接成功后发送的

不知道作者你能不能有空加一下我的微信或者QQ：1573636056  可以交流更便捷。。

**Comment by vitechliu** [comment]
> 作者你看着第一行，这是chrome抓取的包的一部分
> 0000 0044 7b22 7265 7175 6573 745f 7479
> ...D{"request_ty
> 是从7b开始才是 {
> 那前边的00 00 00 44是什么呢
> 
> 而且我给wss发送{……}这样式的数据没有回应，里面的requestid是用13位时间戳模1234567，是不是我在这个地方有什么问题
> 发送的是{"request_type":"1004","cfg_type":1,"requestid":1121338,"platform":0}这一段，是在链接成功后发送的
> 
> 不知道作者你能不能有空加一下我的微信或者QQ：1573636056 可以交流更便捷。。

https://gitter.im/zhuoyao_radar/community 我在gitter。平常没空，wss部分我也没有测试过非web端
