### ISSUE TITLE
接口滥用的疑问.

### ISSUE THREAD

**Issue by quietUncle** [liuzirui1122/zhuoyao_radar#44]
看了下这套捉妖雷达的实现,设计的task+重连机制,确实很完善.

然而自带大范围搜索+无限重连+超时自动重连机制,这一波操作之下,会不会也是属于滥用接口的一环?

而且...现在这个网页应该是流传的最广的....

**Comment by vitechliu** [comment]
因为无限扫接口真的不难，现在有一些盗版雷达各种付费和暗示虚拟定位（比如百度搜捉妖雷达网页版第一的那个），还有很多背后的工作室雷达。
本产品如果不通过提高可用性争夺话语权，反而不利于游戏环境。腾讯根本不整治坐标群。
我觉得哪怕接口彻底崩了也无所谓吧。其实主要是不知道腾讯那边控制接口的怎么想的。

**Comment by vitechliu** [comment]
说句不好听的 我这个开源项目179个fork 这些人一大半都想拿去做坐标或者盈利。市面上流传最广的是我这个雷达已经很幸运了，如果是一个坐标雷达，接口早就被腾讯封了

**Comment by quietUncle** [comment]
了解~
