### ISSUE TITLE
我用你的源码，改了妖灵版本，直接用了哦！

### ISSUE THREAD

**Issue by hibobo** [liuzirui1122/zhuoyao_radar#51]

**Comment by sweet2o09** [comment]
@hibobo 怎么获取新的妖灵版本?

**Comment by hibobo** [comment]
抓包啊

**Comment by ChuckRaind** [comment]
请问大佬，现在需要用token和openid，需要修改哪个地方才可以使用？另外问问怎么抓新妖的数据，谢谢

**Comment by hibobo** [comment]
socket.js 里面initSocketMessage里面加gwgo_token, openid, appid
抓包啊 具体哪个接口忘了

**Comment by ChuckRaind** [comment]
> socket.js 里面initSocketMessage里面加gwgo_token, openid, appid
> 抓包啊 具体哪个接口忘了

是直接在每个Case里加入gwgo_token, openid, appid这三个参数吗？
