### ISSUE TITLE
机器人工作不正常

### ISSUE THREAD

**Issue by Frenqy** [liuzirui1122/zhuoyao_radar#9]
群里能接收到欢迎信息，但是接收不到妖灵信息

**Comment by vitechliu** [comment]
请确保master分支更新到最新版。
长时间没有也正常，小范围搜索稀有怪本来就少

**Comment by Frenqy** [comment]
刚刚更新了一次，依旧不行。
手动在地图上筛选了一次，看到有稀有怪了，执行运行机器人的方法还是只有初始欢迎信息。

**Comment by vitechliu** [comment]
> 刚刚更新了一次，依旧不行。
> 手动在地图上筛选了一次，看到有稀有怪了，执行运行机器人的方法还是只有初始欢迎信息。

大概率是你的经纬度填错了。要么填反了 要么小数点不够

**Comment by Frenqy** [comment]
问题已解决，是经纬度填错了
我看到debug窗口打印的经纬度是没有小数点的，以为机器人里面填的也不需要，所以直接复制过去了
